name: edgex-demo
version: '0.1'
summary: Edgex instance with Grafana and InfluxDB
description: |
  Edgex + Grafana + Influxdb

grade: devel
confinement: strict

parts:
  go:
    source-tag: go1.10.1
    source-depth: 1
  influxdb:
    after: [go]
    source: .
    plugin: go
    go-importpath: github.com/anonymouse67/edgex-web-demo
    build-packages: [mercurial]

apps:
  influxproxy:
    command: bin/influxdbclientserver
    plugs:
      - network-bind
      - network