name: edgex-demo
version: '0.1'
summary: Edgex instance with Grafana and InfluxDB
description: |
  Edgex + Grafana + Influxdb

grade: devel
confinement: strict

parts:
  go:
    source-tag: go1.10.1
    source-depth: 1
  influxproxy:
    after: [go]
    source: .
    plugin: go
    go-importpath: github.com/anonymouse64/edgex-web-demo
    build-packages: [mercurial]
  scripts:
    source: scripts
    plugin: dump
    organize:
      '*.sh': bin/
    prime:
      - bin


apps:
  influxproxy:
    command: bin/runserver.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind
      - network