name: edgex-influx-proxy
version: "replace-me"
version-script: |
  echo 0.7.1-$(git rev-parse --short HEAD)
title: EdgeX Foundry InfluxDB Proxy Server
license: GPL-3.0
summary: Proxy data from EdgeX device services to InfluxDB using export-distro
base: core18
description: |
  The EdgeX InfluxDB Proxy server provides a simple HTTP endpoint that is
  registered with the export-distro EdgeX microservice, forwarding all event
  readings to an InfluxDB server.

grade: stable
confinement: strict

parts:
  influxproxy:
    source: .
    plugin: go
    # TODO: if we ever have other commands we need to build, we will have to
    # switch to using override-build, see
    # https://bugs.launchpad.net/snapcraft/+bug/1858494
    source-subdir: cmd/influxproxy
    build-packages: [mercurial, git, build-essential]
    go-importpath: github.com/anonymouse64/edgex-influx-proxy
  scripts:
    source: scripts
    plugin: dump
    organize:
      "*.sh": bin/
    prime:
      - bin

apps:
  influxproxy:
    command: bin/runserver.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind
      - network
