name: edgex-influx-proxy
version: '0.1'
summary: Edgex export-distro translation to InfluxDB format
base: core18
description: |
  edgex-influx-proxy provides a simple service that listens for EdgeX data from export-distro and 
  formats and forwards that data into InfluxDB.

grade: stable
confinement: strict

parts:
  influxproxy:
    source: .
    plugin: go
    build-packages: [mercurial, git, build-essential]
    override-pull: |
      # we have to do this currently because the default go part does
      # go get -t -d -v ./... which fails because influxdb doesn't have the 
      # needed import path on the master branch which is what the go plugin
      # tries to use
      ROOT_PROJECT_DIR=$(dirname $(dirname $(dirname $SNAPCRAFT_PART_SRC)))
      case $SNAPCRAFT_BUILD_ENVIRONMENT in 
        host)
          # for host build env we don't have a project specific dir
          # so we have to copy everything, filtering out the 
          # snapcraft generated directories
          for dir in $(ls $ROOT_PROJECT_DIR); do
            case $dir in
              parts|prime|stage)
                continue;;
              *)
                cp -r $ROOT_PROJECT_DIR/$dir $SNAPCRAFT_PART_SRC;;
            esac
          done
          ;;
        *)
          # other build environments we will have a project dir that contains
          # only the files from the original project
          cp -r $ROOT_PROJECT_DIR/project/* $SNAPCRAFT_PART_SRC
          ;;
      esac
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cd $SNAPCRAFT_PART_SRC
      go build -o $SNAPCRAFT_PART_INSTALL/bin/influxproxy ./cmd/influxproxy
  scripts:
    source: scripts
    plugin: dump
    organize:
      '*.sh': bin/
    prime:
      - bin

apps:
  influxproxy:
    command: bin/runserver.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind
      - network
