name: edgex-influx-proxy
version: '0.1'
summary: Edgex export-distro translation to InfluxDB format
description: |
  edgex-influx-proxy provides a simple service that listens for EdgeX data from export-distro and 
  formats and forwards that data into InfluxDB.

grade: stable
confinement: strict

parts:
  go:
    source-tag: go1.10.1
    source-depth: 1
  influxproxy:
    after: [go]
    source: .
    plugin: go
    go-importpath: github.com/anonymouse64/edgex-influx-proxy
    build-packages: [mercurial]
  scripts:
    source: scripts
    plugin: dump
    organize:
      '*.sh': bin/
    prime:
      - bin


apps:
  influxproxy:
    command: bin/runserver.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind
      - network